services:

  eureka-service:
    build:
      context: .
      dockerfile: ./eureka-service/Dockerfile
    ports:
      - "${EUREKA_SERVICE_PORT}:${EUREKA_SERVICE_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8761/ || exit 1" ]
      interval: 1s
      timeout: 3s
      retries: 10

  resource-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${RESOURCE_DB_NAME}
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
      PGPORT: ${RESOURCE_DB_PORT}
    ports:
      - "${RESOURCE_DB_PORT}:${RESOURCE_DB_PORT}"
    volumes:
      - ./init-scripts/resource-db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${RESOURCE_DB_USER}" ]
      interval: 1s
      timeout: 3s
      retries: 10

  song-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${SONG_DB_NAME}
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
      PGPORT: ${SONG_DB_PORT}
    ports:
      - "${SONG_DB_PORT}:${SONG_DB_PORT}"
    volumes:
      - ./init-scripts/song-db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${SONG_DB_USER}" ]
      interval: 1s
      timeout: 3s
      retries: 10

  gateway-service:
    build:
      context: .
      dockerfile: ./gateway-service/Dockerfile
    depends_on:
      eureka-service:
        condition: service_healthy
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-service:${EUREKA_SERVICE_PORT}/eureka/

  resource-service:
    build:
      context: .
      dockerfile: ./resource-service/Dockerfile
    depends_on:
      resource-db:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    ports:
      - ${RESOURCE_SERVICE_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_SERVICE_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_PASSWORD}
      SONG_SERVICE_URL: ${SONG_SERVICE_URL}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-service:${EUREKA_SERVICE_PORT}/eureka/

  song-service:
    build:
      context: .
      dockerfile: ./song-service/Dockerfile
    depends_on:
      song-db:
        condition: service_healthy
      eureka-service:
        condition: service_healthy
    ports:
      - ${SONG_SERVICE_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${SONG_SERVICE_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_PASSWORD}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka-service:${EUREKA_SERVICE_PORT}/eureka/
