services:
  resource-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${RESOURCE_DB_NAME}
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    ports:
      - "${RESOURCE_DB_PORT}:5432"

  song-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${SONG_DB_NAME}
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    ports:
      - "${SONG_DB_PORT}:5432"
    volumes:
      - ./init-scripts/song-db/:/docker-entrypoint-initdb.d/

  song-service:
    build:
      context: .
      dockerfile: ./song-service/Dockerfile





#        ./init.sql:/docker-entrypoint-initdb.d/init.sql

# Related settings for application.properties:
#
# For resource-service:
# spring.datasource.url=jdbc:postgresql://localhost:5432/resource-db
# spring.datasource.username=postgres
# spring.datasource.password=postgres
#
# For song-service:
# spring.datasource.url=jdbc:postgresql://localhost:5433/song-db
# spring.datasource.username=postgres
# spring.datasource.password=postgres
