spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: resource-service
              uri:
                lb://RESOURCE-SERVICE
              predicates:
                - Path=/resources/**
            - id: song-service
              uri:
                lb://SONG-SERVICE
              predicates:
                - Path=/songs/**
  servlet:
    encoding:
      enabled: false

server:
  port: 8090