spring.application.name=resource-service

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/resource-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

song.service.url=http://localhost:8085/songs